import {
    addSpaceBeforeAndAfterPunctuation,
    addSpaceBetweenArabicTextAndNumbers,
    applySmartQuotes,
    arabicNumeralToNumber,
    cleanExtremeArabicUnderscores,
    cleanLiteralNewLines,
    cleanMultilines,
    cleanSpacesBeforePeriod,
    cleanSymbolsAndPartReferences,
    cleanTrailingPageNumbers,
    condenseAsterisks,
    condenseColons,
    condenseDashes,
    condenseEllipsis,
    condensePeriods,
    condenseUnderscores,
    convertUrduSymbolsToArabic,
    countWords,
    doubleToSingleBrackets,
    ensureSpaceBeforeBrackets,
    ensureSpaceBeforeQuotes,
    escapeRegex,
    estimateTokenCount,
    extractInitials,
    findLastPunctuation,
    fixBracketTypos,
    fixCurlyBraces,
    fixMismatchedQuotationMarks,
    fixTrailingWow,
    formatStringBySentence,
    getArabicScore,
    hasWordInSingleLine,
    insertLineBreaksAfterPunctuation,
    isAllUppercase,
    isArabicDiacritic,
    isArabicLetter,
    isBalanced,
    isJsonStructureValid,
    isLatinLetter,
    isOnlyPunctuation,
    makeDiacriticInsensitive,
    makeDiacriticInsensitiveRegex,
    normalize,
    normalizeArabicPrefixesToAl,
    normalizeDoubleApostrophes,
    normalizeJsonSyntax,
    normalizeSlashInReferences,
    normalizeSpaces,
    normalizeTransliteratedEnglish,
    parsePageRanges,
    preformatArabicText,
    reduceMultilineBreaksToDouble,
    reduceMultilineBreaksToSingle,
    removeAllTags,
    removeArabicPrefixes,
    removeDeathYear,
    removeMarkdownFormatting,
    removeNonIndexSignatures,
    removeNumbersAndDashes,
    removeRedundantPunctuation,
    removeSingleDigitReferences,
    removeSingularCodes,
    removeSolitaryArabicLetters,
    removeSpaceInsideBrackets,
    removeUrls,
    replaceDoubleBracketsWithArrows,
    replaceEnglishPunctuationWithArabic,
    replaceLineBreaksWithSpaces,
    replaceSalutationsWithSymbol,
    splitByQuotes,
    stripAllDigits,
    stripBoldStyling,
    stripItalicsStyling,
    stripStyling,
    timeToSeconds,
    toTitleCase,
    trimSpaceInsideQuotes,
    truncate,
    truncateMiddle,
    unescapeSpaces,
} from '../../src/index';

export type DemoFunction = {
    name: string;
    description: string;
    sample: string;
    arguments?: string;
    comparison?: string;
    formatter: (input: string) => unknown;
};

type FunctionGroup = {
    title: string;
    description: string;
    items: DemoFunction[];
};

export const functionGroups: FunctionGroup[] = [
    {
        title: 'Arabic helpers',
        description: 'String utilities that understand Arabic script and punctuation.',
        items: [
            {
                name: 'isArabicDiacritic',
                description: 'Check the code point of the first input character for an Arabic diacritic.',
                sample: 'َ',
                comparison: 'م',
                arguments: '.codePointAt(0) ?? 0',
                formatter: (input) => isArabicDiacritic(input.codePointAt(0) ?? 0),
            },
            {
                name: 'isLatinLetter',
                description: 'Check whether one character is a lowercase ASCII letter (a–z).',
                sample: 'a',
                comparison: 'A',
                formatter: isLatinLetter,
            },
            {
                name: 'isArabicLetter',
                description: 'Check whether one character is in the supported Arabic letter ranges.',
                sample: 'م',
                comparison: 'A',
                formatter: isArabicLetter,
            },
            {
                name: 'estimateTokenCount',
                description:
                    'Estimate token count with the generic provider heuristic. This is an approximation, not a tokenizer.',
                sample: 'بِسْمِ اللَّهِ Hello world 2024',
                formatter: estimateTokenCount,
            },
            {
                name: 'countWords',
                description: 'Count whitespace-separated words in Arabic, English or mixed text.',
                sample: 'مرحبا بالعالم Hello world',
                formatter: countWords,
            },
            {
                name: 'arabicNumeralToNumber',
                description: 'Convert Arabic-Indic numerals to a JavaScript number.',
                sample: '١٢٣',
                formatter: (input) => arabicNumeralToNumber(input),
            },
            {
                name: 'cleanExtremeArabicUnderscores',
                description: 'Remove one edge tatweel character per line, preserving Hijri year suffixes.',
                sample: 'ـالحمد لله رب العالمينـ\nعام 1444هـ',
                formatter: cleanExtremeArabicUnderscores,
            },
            {
                name: 'convertUrduSymbolsToArabic',
                description: 'Map Urdu glyph variants (ھ، ی) to Arabic equivalents.',
                sample: 'ھذا یوم جمیل',
                formatter: convertUrduSymbolsToArabic,
            },
            {
                name: 'getArabicScore',
                description: 'Measure the Arabic character ratio from 0 to 1, excluding whitespace and digits.',
                sample: 'مرحبا Hello 123',
                formatter: (input) => getArabicScore(input),
            },
            {
                name: 'findLastPunctuation',
                description: 'Find the last punctuation mark index in a string.',
                sample: 'مرحبا بالعالم! كيف الحال؟',
                formatter: (input) => findLastPunctuation(input),
            },
            {
                name: 'fixTrailingWow',
                description: 'Attach a standalone و to the following word: و رحمة → ورحمة.',
                sample: 'السلام عليكم و رحمة الله',
                formatter: fixTrailingWow,
            },
            {
                name: 'addSpaceBetweenArabicTextAndNumbers',
                description: 'Insert a space between Arabic text segments and numbers.',
                sample: 'الآية37 في الصفحة2',
                formatter: addSpaceBetweenArabicTextAndNumbers,
            },
            {
                name: 'removeNonIndexSignatures',
                description: 'Remove non-index digits and stray dashes between Arabic text.',
                sample: 'وهب 3 وقال - في الكتاب',
                formatter: removeNonIndexSignatures,
            },
            {
                name: 'removeSingularCodes',
                description: 'Remove a single Arabic letter or Arabic-Indic digit enclosed in (), [] or {}.',
                sample: 'قال [س] و (٣) في النص',
                formatter: removeSingularCodes,
            },
            {
                name: 'removeSolitaryArabicLetters',
                description: 'Remove isolated Arabic letters separated by spaces. This also removes isolated ه.',
                sample: 'ب النص ت الكتاب',
                formatter: removeSolitaryArabicLetters,
            },
            {
                name: 'replaceEnglishPunctuationWithArabic',
                description: 'Replace ASCII punctuation with Arabic equivalents.',
                sample: 'لماذا? هذا مهم; جدا, نعم',
                formatter: replaceEnglishPunctuationWithArabic,
            },
        ],
    },
    {
        title: 'Cleaning & tolerant matching',
        description: 'Sanitization helpers for markdown, URLs, digits, and tolerant matching.',
        items: [
            {
                name: 'escapeRegex',
                description: 'Escape special characters for safe regex creation.',
                sample: 'Find (this) + [that]',
                formatter: escapeRegex,
            },
            {
                name: 'makeDiacriticInsensitiveRegex',
                description: 'Build a regex tolerant of Arabic diacritics and variants.',
                sample: 'أنا إلى الآفاق',
                formatter: (input) => makeDiacriticInsensitiveRegex(input),
            },
            {
                name: 'makeDiacriticInsensitive',
                description: 'Create a diacritic-insensitive pattern string.',
                sample: 'أنا إلى الآفاق',
                formatter: makeDiacriticInsensitive,
            },
            {
                name: 'removeAllTags',
                description: 'Strip HTML/XML tags from text.',
                sample: '<p>Hello <strong>world</strong></p>',
                formatter: removeAllTags,
            },
            {
                name: 'cleanSymbolsAndPartReferences',
                description: 'Replace ornaments, punctuation and ASCII numeric references with spaces.',
                sample: 'قال المؤلف (1) [2/3] في الكتاب؛ ثم أكمل.',
                formatter: cleanSymbolsAndPartReferences,
            },
            {
                name: 'cleanTrailingPageNumbers',
                description: 'Drop trailing -[123]- style page markers.',
                sample: 'هذا نص -[123]-',
                formatter: cleanTrailingPageNumbers,
            },
            {
                name: 'replaceLineBreaksWithSpaces',
                description: 'Collapse whitespace and line breaks to single spaces.',
                sample: 'Line one\n\nLine two',
                formatter: replaceLineBreaksWithSpaces,
            },
            {
                name: 'stripAllDigits',
                description: 'Remove ASCII digits from the input.',
                sample: 'Version 2.0 لعام 2024',
                formatter: stripAllDigits,
            },
            {
                name: 'removeDeathYear',
                description: 'Strip (d. ####H) style death-year mentions.',
                sample: 'الإمام (d. 1444H) قال',
                formatter: removeDeathYear,
            },
            {
                name: 'removeNumbersAndDashes',
                description: 'Remove ASCII digits and hyphens; Arabic-Indic digits remain.',
                sample: 'صفحة 12-13 في 2024',
                formatter: removeNumbersAndDashes,
            },
            {
                name: 'removeSingleDigitReferences',
                description: 'Delete single digit markers like (1), [2], «3».',
                sample: 'هذا نص (1) [2] «3»',
                formatter: removeSingleDigitReferences,
            },
            {
                name: 'removeUrls',
                description: 'Remove http(s) URLs from text.',
                sample: 'Read more at https://example.com الآن',
                formatter: removeUrls,
            },
            {
                name: 'removeMarkdownFormatting',
                description: 'Drop markdown bold/italic/link/list syntax.',
                sample: '**Bold** _italic_ [link](https://example.com)',
                formatter: removeMarkdownFormatting,
            },
            {
                name: 'truncate',
                description: 'Limit output to 24 characters, including the final ellipsis, in this example.',
                sample: 'This is a long sentence that will be cut to size.',
                arguments: ', 24',
                formatter: (input) => truncate(input, 24),
            },
            {
                name: 'truncateMiddle',
                description: 'Limit output to 40 characters, preserving the last 12 characters in this example.',
                sample: 'the quick brown fox jumps over the lazy dog',
                arguments: ', 40, 12',
                formatter: (input) => truncateMiddle(input, 40, 12),
            },
            {
                name: 'unescapeSpaces',
                description: 'Convert escaped spaces (\\ ) back to regular spaces.',
                sample: 'Hello\\ world\\ ',
                formatter: unescapeSpaces,
            },
        ],
    },
    {
        title: 'Formatting & typography',
        description: 'Spacing, punctuation, and typography normalizers.',
        items: [
            {
                name: 'insertLineBreaksAfterPunctuation',
                description: 'Add line breaks after . ! ? and Arabic ؟ punctuation.',
                sample: 'Hello world! How are you? Great.',
                formatter: insertLineBreaksAfterPunctuation,
            },
            {
                name: 'addSpaceBeforeAndAfterPunctuation',
                description: 'Normalize spacing around punctuation while respecting quotes.',
                sample: 'مرحبا،كيف الحال؟',
                formatter: addSpaceBeforeAndAfterPunctuation,
            },
            {
                name: 'applySmartQuotes',
                description: 'Replace paired straight double quotes with curly double quotes.',
                sample: 'The editor said "Read carefully" and "Take notes".',
                formatter: applySmartQuotes,
            },
            {
                name: 'cleanLiteralNewLines',
                description: 'Convert literal \\n sequences and actual carriage returns to line breaks.',
                sample: 'Chapter one\\nChapter two\\nChapter three',
                formatter: cleanLiteralNewLines,
            },
            {
                name: 'cleanMultilines',
                description: 'Trim horizontal whitespace at both ends of each line, preserving line breaks.',
                sample: 'Line one   \nLine two   ',
                formatter: cleanMultilines,
            },
            {
                name: 'hasWordInSingleLine',
                description: 'Detect whether a line contains a single standalone word.',
                sample: 'Word\nSecond line',
                comparison: 'Every line contains\nmore than one word',
                formatter: (input) => hasWordInSingleLine(input),
            },
            {
                name: 'isOnlyPunctuation',
                description:
                    'Check for only ASCII punctuation, spaces and ASCII / Arabic-Indic digits. Arabic ؟ is not included.',
                sample: '...?! 123',
                comparison: 'مرحبا؟',
                formatter: (input) => isOnlyPunctuation(input),
            },
            {
                name: 'cleanSpacesBeforePeriod',
                description: 'Remove spaces immediately before punctuation marks.',
                sample: 'Hello . World ? ',
                formatter: cleanSpacesBeforePeriod,
            },
            {
                name: 'condenseAsterisks',
                description: 'Collapse multiple asterisks into a single *.',
                sample: 'Look **** here',
                formatter: condenseAsterisks,
            },
            {
                name: 'condenseColons',
                description: 'Remove a dot or dash adjacent to a colon; repeated colons remain.',
                sample: 'Chapter.:. Introduction\nNote-:- Read on',
                formatter: condenseColons,
            },
            {
                name: 'condenseDashes',
                description: 'Reduce consecutive dashes to a single dash.',
                sample: 'well---known',
                formatter: condenseDashes,
            },
            {
                name: 'condenseEllipsis',
                description: 'Convert runs of periods into a single ellipsis.',
                sample: 'Wait.... what',
                formatter: condenseEllipsis,
            },
            {
                name: 'reduceMultilineBreaksToDouble',
                description: 'Limit blank lines to at most two newlines.',
                sample: 'line1\n\n\n\nline2',
                formatter: reduceMultilineBreaksToDouble,
            },
            {
                name: 'reduceMultilineBreaksToSingle',
                description: 'Collapse multiple blank lines to a single newline.',
                sample: 'line1\n\n\nline2',
                formatter: reduceMultilineBreaksToSingle,
            },
            {
                name: 'condensePeriods',
                description: 'Reduce a pair of periods separated by spaces to one period.',
                sample: 'Wait . . before continuing.',
                formatter: condensePeriods,
            },
            {
                name: 'condenseUnderscores',
                description: 'Collapse repeated underscores and tatweel runs.',
                sample: 'هذا____ نص',
                formatter: condenseUnderscores,
            },
            {
                name: 'doubleToSingleBrackets',
                description: 'Replace doubled brackets with single ones.',
                sample: '((text)) [[note]]',
                formatter: doubleToSingleBrackets,
            },
            {
                name: 'ensureSpaceBeforeBrackets',
                description: 'Add or normalize the space before a parenthetical note.',
                sample: 'word(aside)',
                formatter: ensureSpaceBeforeBrackets,
            },
            {
                name: 'ensureSpaceBeforeQuotes',
                description: 'Ensure spacing before Arabic guillemets.',
                sample: 'قال«مرحبا»',
                formatter: ensureSpaceBeforeQuotes,
            },
            {
                name: 'fixBracketTypos',
                description: 'Repair specific guillemet / parenthesis typos and reversed numeric parentheses.',
                sample: '(«مرحبا») reference )12(',
                formatter: fixBracketTypos,
            },
            {
                name: 'fixCurlyBraces',
                description: 'Repair mixed parenthesis / curly brace pairs: (text} and {text).',
                sample: '(chapter title} and {editor note)',
                formatter: fixCurlyBraces,
            },
            {
                name: 'fixMismatchedQuotationMarks',
                description: 'Fix malformed Arabic guillemets and parentheses combos.',
                sample: '«مرحبا")',
                formatter: fixMismatchedQuotationMarks,
            },
            {
                name: 'formatStringBySentence',
                description:
                    'Join wrapped lines into sentences while keeping parenthesized footnotes on their own lines.',
                sample: 'This sentence was\nsplit by OCR.\n(1) An editorial footnote.\nAnother sentence\ncontinues here!',
                formatter: formatStringBySentence,
            },
            {
                name: 'isAllUppercase',
                description: 'Detect whether the text is fully uppercase.',
                sample: 'THIS IS A TITLE',
                comparison: 'This is a title',
                formatter: (input) => isAllUppercase(input),
            },
            {
                name: 'normalizeSlashInReferences',
                description: 'Normalize spaced fractions like 127 / 11 to 127/11.',
                sample: 'بِسْمِ اللَّهِ 127 / 11',
                formatter: normalizeSlashInReferences,
            },
            {
                name: 'normalizeSpaces',
                description: 'Collapse extra spaces and tabs to single spaces.',
                sample: 'This    has    many spaces',
                formatter: normalizeSpaces,
            },
            {
                name: 'removeRedundantPunctuation',
                description: 'Remove a period or Arabic comma immediately after ؟ or !.',
                sample: 'كيف حالك؟. ممتاز!،',
                formatter: removeRedundantPunctuation,
            },
            {
                name: 'removeSpaceInsideBrackets',
                description: 'Trim internal spaces inside brackets or parentheses.',
                sample: '( Fasting is during ) [ the ] winter.',
                formatter: removeSpaceInsideBrackets,
            },
            {
                name: 'replaceDoubleBracketsWithArrows',
                description: 'Convert doubled parentheses to Arabic guillemets: ((text)) → «text».',
                sample: 'قال (( الحمد لله )) ثم أكمل.',
                formatter: replaceDoubleBracketsWithArrows,
            },
            {
                name: 'stripBoldStyling',
                description: 'Remove bold Unicode stylization.',
                sample: '𝗢𝗳 𝗮𝗹𝗹 𝗯𝗼𝗹𝗱 𝘁𝗲𝘅𝘁',
                formatter: stripBoldStyling,
            },
            {
                name: 'stripItalicsStyling',
                description:
                    'Map supported mathematical italic glyphs to plain characters. Other italic alphabets remain unchanged.',
                sample: 'Mathematical letters: 𝑎𝑏𝑐',
                formatter: stripItalicsStyling,
            },
            {
                name: 'stripStyling',
                description: 'Convenience combo of bold + italics stripping.',
                sample: '𝗢𝗳 𝗮𝗹𝗹 𝘀𝘁𝗶𝗽𝘂𝗹𝗮𝘁𝗶𝗼𝗻𝘀 𝘢𝗻𝗱 𝘪𝘵𝘢𝘭𝘪𝘤𝘪𝘻𝘦𝘥 𝘁𝗲𝘅𝘁',
                formatter: stripStyling,
            },
            {
                name: 'toTitleCase',
                description: 'Convert strings to title case with Unicode support.',
                sample: 'the quick brown fox',
                formatter: toTitleCase,
            },
            {
                name: 'trimSpaceInsideQuotes',
                description: 'Remove spaces immediately inside quotes.',
                sample: '“ Fasting is during the winter. ”',
                formatter: trimSpaceInsideQuotes,
            },
        ],
    },
    {
        title: 'Parsing helpers',
        description: 'JSON normalization, quote splitting, and range parsing.',
        items: [
            {
                name: 'timeToSeconds',
                description: 'Convert HH:MM:SS, MM:SS or plain seconds to a number.',
                sample: '01:23:45',
                comparison: '02:30',
                formatter: timeToSeconds,
            },
            {
                name: 'normalizeJsonSyntax',
                description: 'Normalize JSON-like strings with numeric keys and single quotes.',
                sample: "{10: 'abc', 20: 'def'}",
                formatter: normalizeJsonSyntax,
            },
            {
                name: 'isJsonStructureValid',
                description: 'Detect the supported JSON-like key/value shape; this is not a full JSON validator.',
                sample: "{10: 'abc', 'key': 'value'}",
                comparison: '{title: missing quotes}',
                formatter: (input) => isJsonStructureValid(input),
            },
            {
                name: 'splitByQuotes',
                description: 'Split by spaces while preserving quoted substrings.',
                sample: '"This is" "a part" of string',
                formatter: (input) => splitByQuotes(input),
            },
            {
                name: 'isBalanced',
                description: 'Check paired double quotes and properly nested (), [] and {} brackets.',
                sample: 'He said "Hello (world)!"',
                comparison: 'He said "Hello (world]!"',
                formatter: (input) => isBalanced(input),
            },
            {
                name: 'parsePageRanges',
                description: 'Expand range/list strings into numeric arrays.',
                sample: '1-3, 7, 10-12',
                comparison: '5-2',
                formatter: (input) => parsePageRanges(input),
            },
        ],
    },
    {
        title: 'Transliteration',
        description: 'Normalize transliterated Arabic text and salutations.',
        items: [
            {
                name: 'normalizeArabicPrefixesToAl',
                description: 'Standardize supported definite article prefixes such as Ash-S, Ar- and Al to al-.',
                sample: 'Ash-Shafiee Ar-Rahman Al Bukhari',
                formatter: normalizeArabicPrefixesToAl,
            },
            {
                name: 'normalizeDoubleApostrophes',
                description: 'Collapse duplicated Arabic apostrophes in transliteration.',
                sample: 'ʿʿabd al-ʿʿaziz',
                formatter: normalizeDoubleApostrophes,
            },
            {
                name: 'replaceSalutationsWithSymbol',
                description:
                    'Replace Arabic, transliterated and English prophetic salutations with ﷺ, preserving line breaks.',
                sample: 'قال النبي صلى الله عليه وسلم: إنما الأعمال بالنيات.\nThe Prophet (PBUH) taught kindness.',
                formatter: replaceSalutationsWithSymbol,
            },
            {
                name: 'normalize',
                description: 'Strip diacritics, apostrophes, and dashes from transliteration.',
                sample: 'al-ḥadīth',
                formatter: normalize,
            },
            {
                name: 'removeArabicPrefixes',
                description: 'Remove transliteration prefixes like al-, wa-, bi-, li-.',
                sample: 'al-quran wa-rahma',
                formatter: removeArabicPrefixes,
            },
            {
                name: 'normalizeTransliteratedEnglish',
                description: 'Combine prefix removal + diacritic stripping.',
                sample: 'al-ḥadīth wa-l-ḥaqq',
                formatter: normalizeTransliteratedEnglish,
            },
            {
                name: 'extractInitials',
                description: 'Extract initials from up to two transliterated words.',
                sample: 'Muhammad ibn Abdullah',
                formatter: extractInitials,
            },
        ],
    },
    {
        title: 'Preformatting pipeline',
        description: 'Single-pass formatter optimized for large Arabic text.',
        items: [
            {
                name: 'preformatArabicText',
                description:
                    'Clean Arabic spacing, punctuation, brackets and line breaks together, preserving numeric references.',
                sample: 'بِسْمِ  اللَّهِ ( الرَّحْمَنِ )\nقال:هذا نص،يحتاج إلى تنسيق!\nالمرجع 127 / 11 والآية 2:255.',
                formatter: (input) => preformatArabicText(input),
            },
        ],
    },
];

export const allFunctions = functionGroups.flatMap((group) => group.items);

export const mockTexts = [
    {
        label: 'Arabic manuscript',
        text: 'قال النبي صلى الله عليه وسلم:إنما الأعمال بالنيات.\n(1) المصدر 127 / 11.\nھذا نص  فيه   مسافات و أخطاء،يحتاج إلى مراجعة؟.',
    },
    {
        label: 'Bilingual article',
        text: '# Editorial notes\n**Al-ḥadīth** means "the narration".\nRead more at https://example.com/article (1).\nمرحبا،كيف الحال? Version 2024.',
    },
];
